[package]
name = "ruzstd"
version = "0.3.1"
authors = ["Moritz Borcherding <moritz.borcherding@web.de>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/KillingSpark/zstd-rs"
repository = "https://github.com/KillingSpark/zstd-rs"
description = "A decoder for the zstd compression format"
exclude = ["decodecorpus_files/*", "dict_tests/*", "fuzz_decodecorpus/*"]
readme = "Readme.md"

[dependencies]
byteorder = "1.4"
twox-hash = { version = "1.6", default-features = false }
thiserror = "1"

[dev-dependencies]
criterion = "0.3"
rand = "0.8.5"

[[bench]]
name = "reversedbitreader_bench"
harness = false
